# TCL File Generated by Component Editor 13.1
# Tue Nov 14 17:32:21 GMT+03:00 2017
# DO NOT MODIFY


# 
# owm_avalon_slave "Avalon 1-wire Master" v1.0
# Aleksey Golovchenko 2017.11.14.17:32:21
# Avalon 1-wire Master
# 

# 
# request TCL package from ACDS 13.1
# 
package require -exact qsys 13.1


# 
# module owm_avalon_slave
# 
set_module_property DESCRIPTION "Avalon 1-wire Master"
set_module_property NAME owm_avalon_slave
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property GROUP "My IP"
set_module_property AUTHOR "Aleksey Golovchenko"
set_module_property DISPLAY_NAME "Avalon 1-wire Master"
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property ANALYZE_HDL AUTO
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL owm_avalon_slave
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
add_fileset_file owm.sv SYSTEM_VERILOG PATH owm.sv
add_fileset_file owm_avalon_slave.sv SYSTEM_VERILOG PATH owm_avalon_slave.sv TOP_LEVEL_FILE
add_fileset_file owm_avalon_slave_interface.sv SYSTEM_VERILOG PATH owm_avalon_slave_interface.sv

add_fileset SIM_VERILOG SIM_VERILOG "" ""
set_fileset_property SIM_VERILOG TOP_LEVEL owm_avalon_slave
set_fileset_property SIM_VERILOG ENABLE_RELATIVE_INCLUDE_PATHS false
add_fileset_file owm.sv SYSTEM_VERILOG PATH owm.sv
add_fileset_file owm_avalon_slave.sv SYSTEM_VERILOG PATH owm_avalon_slave.sv
add_fileset_file owm_avalon_slave_interface.sv SYSTEM_VERILOG PATH owm_avalon_slave_interface.sv

add_fileset SIM_VHDL SIM_VHDL "" ""
set_fileset_property SIM_VHDL TOP_LEVEL owm_avalon_slave
set_fileset_property SIM_VHDL ENABLE_RELATIVE_INCLUDE_PATHS false
add_fileset_file owm.sv SYSTEM_VERILOG PATH owm.sv
add_fileset_file owm_avalon_slave.sv SYSTEM_VERILOG PATH owm_avalon_slave.sv
add_fileset_file owm_avalon_slave_interface.sv SYSTEM_VERILOG PATH owm_avalon_slave_interface.sv


# 
# parameters
# 
add_parameter OW_BUS_NUM NATURAL 4 "Number of 1-wire buses"
set_parameter_property OW_BUS_NUM DEFAULT_VALUE 4
set_parameter_property OW_BUS_NUM DISPLAY_NAME OW_BUS_NUM
set_parameter_property OW_BUS_NUM WIDTH ""
set_parameter_property OW_BUS_NUM TYPE NATURAL
set_parameter_property OW_BUS_NUM UNITS None
set_parameter_property OW_BUS_NUM ALLOWED_RANGES 0:2147483647
set_parameter_property OW_BUS_NUM DESCRIPTION "Number of 1-wire buses"
set_parameter_property OW_BUS_NUM HDL_PARAMETER true


# 
# display items
# 


# 
# connection point avalon_slave_0
# 
add_interface avalon_slave_0 avalon end
set_interface_property avalon_slave_0 addressUnits WORDS
set_interface_property avalon_slave_0 associatedClock clock_sink
set_interface_property avalon_slave_0 associatedReset reset_sink
set_interface_property avalon_slave_0 bitsPerSymbol 8
set_interface_property avalon_slave_0 burstOnBurstBoundariesOnly false
set_interface_property avalon_slave_0 burstcountUnits WORDS
set_interface_property avalon_slave_0 explicitAddressSpan 0
set_interface_property avalon_slave_0 holdTime 0
set_interface_property avalon_slave_0 linewrapBursts false
set_interface_property avalon_slave_0 maximumPendingReadTransactions 0
set_interface_property avalon_slave_0 readLatency 0
set_interface_property avalon_slave_0 readWaitTime 1
set_interface_property avalon_slave_0 setupTime 0
set_interface_property avalon_slave_0 timingUnits Cycles
set_interface_property avalon_slave_0 writeWaitTime 0
set_interface_property avalon_slave_0 ENABLED true
set_interface_property avalon_slave_0 EXPORT_OF ""
set_interface_property avalon_slave_0 PORT_NAME_MAP ""
set_interface_property avalon_slave_0 CMSIS_SVD_VARIABLES ""
set_interface_property avalon_slave_0 SVD_ADDRESS_GROUP ""

add_interface_port avalon_slave_0 addr_i address Input 4
add_interface_port avalon_slave_0 write_i write Input 1
add_interface_port avalon_slave_0 read_i read Input 1
add_interface_port avalon_slave_0 wrdata_i writedata Input 32
add_interface_port avalon_slave_0 rddata_o readdata Output 32
set_interface_assignment avalon_slave_0 embeddedsw.configuration.isFlash 0
set_interface_assignment avalon_slave_0 embeddedsw.configuration.isMemoryDevice 0
set_interface_assignment avalon_slave_0 embeddedsw.configuration.isNonVolatileStorage 0
set_interface_assignment avalon_slave_0 embeddedsw.configuration.isPrintableDevice 0


# 
# connection point clock_sink
# 
add_interface clock_sink clock end
set_interface_property clock_sink clockRate 0
set_interface_property clock_sink ENABLED true
set_interface_property clock_sink EXPORT_OF ""
set_interface_property clock_sink PORT_NAME_MAP ""
set_interface_property clock_sink CMSIS_SVD_VARIABLES ""
set_interface_property clock_sink SVD_ADDRESS_GROUP ""

add_interface_port clock_sink clk_i clk Input 1


# 
# connection point reset_sink
# 
add_interface reset_sink reset end
set_interface_property reset_sink associatedClock clock_sink
set_interface_property reset_sink synchronousEdges DEASSERT
set_interface_property reset_sink ENABLED true
set_interface_property reset_sink EXPORT_OF ""
set_interface_property reset_sink PORT_NAME_MAP ""
set_interface_property reset_sink CMSIS_SVD_VARIABLES ""
set_interface_property reset_sink SVD_ADDRESS_GROUP ""

add_interface_port reset_sink rst_i reset Input 1


# 
# connection point interrupt_sender
# 
add_interface interrupt_sender interrupt end
set_interface_property interrupt_sender associatedAddressablePoint ""
set_interface_property interrupt_sender associatedClock clock_sink
set_interface_property interrupt_sender associatedReset reset_sink
set_interface_property interrupt_sender ENABLED true
set_interface_property interrupt_sender EXPORT_OF ""
set_interface_property interrupt_sender PORT_NAME_MAP ""
set_interface_property interrupt_sender CMSIS_SVD_VARIABLES ""
set_interface_property interrupt_sender SVD_ADDRESS_GROUP ""

add_interface_port interrupt_sender irq_o irq Output 1


# 
# connection point owr
# 
add_interface owr conduit end
set_interface_property owr associatedClock clock_sink
set_interface_property owr associatedReset reset_sink
set_interface_property owr ENABLED true
set_interface_property owr EXPORT_OF ""
set_interface_property owr PORT_NAME_MAP ""
set_interface_property owr CMSIS_SVD_VARIABLES ""
set_interface_property owr SVD_ADDRESS_GROUP ""

add_interface_port owr ow_i export Input OW_BUS_NUM
add_interface_port owr ow_o export Output OW_BUS_NUM

